### ISSUE TITLE
As an admin, I want to sumbit my products

### ISSUE THREAD

**Issue by FranckG28** [Livl-Corporation/livl-reviews-api#11]
I want a HTTPS route to submit my product.

Route info : https://www.notion.so/franckg/Routes-5b06a36671a84048b95720aa46622ff4?pvs=4#6fa11139c0104c1d9b33c28cc6a3ab0d

**Comment by raffaeldp** [comment]
Need to specify Product type to see how to compare two product to see if it has been deleted.

**Comment by raffaeldp** [comment]
Do we really want to add / edit products directly before arriving to the last page ? 
Because if we interupt the sending, we are not hitting the page === totalPage condition, and we may have undeleted products as the "deletion phase" has not been done.

Shouldn't we add to cache each request, and then when we got everything, we do the add / edit / delete stuff ? 

Or we say that it will be rare to have an interruption and we don't care about undeleted products.

And so, we only reset cache when starting a posting batch again (page === 0)
